// @flow
export const GOTAPIDATA = 'GOTAPIDATA';
export const UPDATEAPIDATA = 'UPDATEAPIDATA';
export const GETSEATDATA = 'GETSEATDATA';
export const SESSIONDATA = 'SESSIONDATA';
export const BOOKINGOBJINFO = 'BOOKINGOBJINFO';
export const CHANGETAB = 'CHANGETAB';
export const NUMERICCOUNT = 'NUMERICCOUNT';
export const FORMITEMS = 'FORMITEMS';
export const SELECTEDSEATS = 'SELECTEDSEATS';
export const UPDATELAYOUT = 'UPDATELAYOUT';
export const MODALACTION = 'MODALACTION';
export const OPTIONLISTDATA = 'OPTIONLISTDATA';
export const TOGGLEDATA = 'TOGGLEDATA';
export const GETLOGINDATA = 'GETLOGINDATA';
export const UPDATELOGININFO = 'UPDATELOGININFO';
export const LOGOUT = 'LOGOUT';
export const SELECTEDFREESEATS = 'SELECTEDFREESEATS';
export const GETSALESHISTORYDATA = 'GETSALESHISTORYDATA';
export const GETFNBCATEGORY = 'GETFNBCATEGORY';
export const GETALLLIST = 'GETALLLIST';
export const GETMOSTPOPULAR = 'GETMOSTPOPULAR';

